// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_chat_snapshot_internal`, `import_chat_update_internal`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GLOBAL_DOC`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> resetGlobalDoc() => RustLib.instance.api.crateApiResetGlobalDoc();

Future<String> decodeMessageSnapshot({required String snapshotBase64}) =>
    RustLib.instance.api
        .crateApiDecodeMessageSnapshot(snapshotBase64: snapshotBase64);

Future<String> decodeChatSnapshot({required String snapshotBase64}) =>
    RustLib.instance.api
        .crateApiDecodeChatSnapshot(snapshotBase64: snapshotBase64);

Future<String> importChatUpdate({required List<int> updateBytes}) =>
    RustLib.instance.api.crateApiImportChatUpdate(updateBytes: updateBytes);
