// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcE4CoDwmwUM_Fe8NGXwmRHS5f-7x1MjM',
    appId: '1:725431248263:web:3ae52fdcf6a71b2d531f22',
    messagingSenderId: '725431248263',
    projectId: 'chating-e5b0b',
    authDomain: 'chating-e5b0b.firebaseapp.com',
    databaseURL: 'https://chating-e5b0b-default-rtdb.firebaseio.com',
    storageBucket: 'chating-e5b0b.firebasestorage.app',
    measurementId: 'G-V82MVR7VFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1U4_g_pU6y0-6kD35PSS8DumrcuTGdE',
    appId: '1:725431248263:android:ea5d90b0edc3cc96531f22',
    messagingSenderId: '725431248263',
    projectId: 'chating-e5b0b',
    databaseURL: 'https://chating-e5b0b-default-rtdb.firebaseio.com',
    storageBucket: 'chating-e5b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN_ZDrZCvGIivXQCuhWdy7wNztqtMjf34',
    appId: '1:725431248263:ios:d27c9f98203f1c40531f22',
    messagingSenderId: '725431248263',
    projectId: 'chating-e5b0b',
    databaseURL: 'https://chating-e5b0b-default-rtdb.firebaseio.com',
    storageBucket: 'chating-e5b0b.firebasestorage.app',
    iosBundleId: 'com.nowdigitaleasy.NDEconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN_ZDrZCvGIivXQCuhWdy7wNztqtMjf34',
    appId: '1:725431248263:ios:762882593e448ef6531f22',
    messagingSenderId: '725431248263',
    projectId: 'chating-e5b0b',
    databaseURL: 'https://chating-e5b0b-default-rtdb.firebaseio.com',
    storageBucket: 'chating-e5b0b.firebasestorage.app',
    iosBundleId: 'com.example.ndeEmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcE4CoDwmwUM_Fe8NGXwmRHS5f-7x1MjM',
    appId: '1:725431248263:web:dab22d4f890e5e7f531f22',
    messagingSenderId: '725431248263',
    projectId: 'chating-e5b0b',
    authDomain: 'chating-e5b0b.firebaseapp.com',
    databaseURL: 'https://chating-e5b0b-default-rtdb.firebaseio.com',
    storageBucket: 'chating-e5b0b.firebasestorage.app',
    measurementId: 'G-W904YES2NE',
  );
}
